Update darkspider.py
PROxZIMA/DarkSpider pull request #26
Opened 2022-10-02 20:35 UTC by ChaveleYellowOwl

I think this could be a cool banner to add to the tool just to flare it up a little bit.

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2022-10-03 15:50 UTC, DexLulz commented
It wasn't a logo I used a photograph of a spider, its on my laptop I can get the original later today if you would like, your tool looks great btw!

2022-10-03 16:18 UTC, PROxZIMA commented
> I used a photograph of a spider
Wohh, I thought it was a logo because the ascii looks so clean.

> your tool looks great btw
Haha, it still lacks tons of features which are mentioned in #23. We are actively working on them.

About this PR, I'll merge it after adding a proper "display in terminal" like banner.

2022-10-03 16:19 UTC, PROxZIMA requested changes

2022-10-03 16:19 UTC, PROxZIMA commented on darkspider.py
> +#I think this banner could be cool for the tool If you like it delete this comment
You can delete this comment.

2022-10-03 16:22 UTC, DexLulz commented on darkspider.py
> +#I think this banner could be cool for the tool If you like it delete this comment
Done

2022-10-03 16:23 UTC, PROxZIMA approved these changes

2023-02-20 21:46 UTC, PROxZIMA commented
Finally got some free time to look into this. Few changes:
- Super cool gradient banner.
![image](https://user-images.githubusercontent.com/43103163/220202758-a784a18b-3642-48cb-b55d-17fd65d809c5.png)
- Colored logger
- Helper module is more modular now.

Just need to test it on windows and it'll be ready to merge!!

2023-02-21 16:24 UTC, merged